---
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Sydney # Change me
    volumes:
      - ./config:/config
    ports:
      - 127.0.0.1:9696:9696
    restart: unless-stopped
    networks:
      - torrent_net

networks:
  torrent_net:
    external: true
