---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 127.0.0.1:8989:8989
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Sydney # Change me
    volumes:
      - ./config:/config
      - ./tv:/tv # Change me
      - ./downloads:/downloads # Change me
    restart: unless-stopped
    networks:
      - torrent_net

networks:
  torrent_net:
    external: true
