---
services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Sydney # Change Me
      - FIREFOX_CLI=https://duckduckgo.com/ #optional
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - torrent_net

networks:
  torrent_net:
    external: true
